"""empty message

Revision ID: 4d6cdc2aef74
Revises: 34bb1410bc65
Create Date: 2016-04-03 15:20:25.594000

"""

# revision identifiers, used by Alembic.
revision = '4d6cdc2aef74'
down_revision = '34bb1410bc65'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fav_color', sa.String(length=155), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fav_color')
    ### end Alembic commands ###
