"""empty message

Revision ID: f823a9c5f4aa
Revises: e43b20096483
Create Date: 2016-04-20 10:17:25.909000

"""

# revision identifiers, used by Alembic.
revision = 'f823a9c5f4aa'
down_revision = 'e43b20096483'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories_posts',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories_posts')
    op.drop_table('categories')
    ### end Alembic commands ###
